package com.sunday.common.exception

interface NotFoundException
interface InsufficientBalanceException
interface AlreadyExistsException
interface DuplicateRequestException
interface ConcurrencyException
interface LockAcquisitionException
interface OutOfStockException
interface HotDealNotActiveException
interface InvalidOrderStatusException
interface OrderNotPayableException
interface PaymentFailedException
